# Generated by Django 2.1.3 on 2018-11-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0002_auto_20181106_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='epgentity',
            name='rating',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
